// <auto-generated />
using System;
using DecisionManagerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DecisionManagerAPI.Migrations
{
    [DbContext(typeof(DecisionManagerDbContext))]
    [Migration("20260327162215_AjoutCardComboTriggerAndCardRequirementsAndCardCombo")]
    partial class AjoutCardComboTriggerAndCardRequirementsAndCardCombo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DecisionManagerAPI.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionFr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayNameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayNameFr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureMessageEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureMessageFr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MotivationEffect")
                        .HasColumnType("integer");

                    b.Property<int>("MotivationEffectOnFailure")
                        .HasColumnType("integer");

                    b.Property<int>("PerformanceEffect")
                        .HasColumnType("integer");

                    b.Property<int>("PerformanceEffectOnFailure")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StressEffect")
                        .HasColumnType("integer");

                    b.Property<int>("StressEffectOnFailure")
                        .HasColumnType("integer");

                    b.Property<string>("SuccessMessageEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuccessMessageFr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("SuccessProbability")
                        .HasColumnType("real");

                    b.Property<int>("TurnoverEffect")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoverEffectOnFailure")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.CardCombo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MessageFr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MotivationDelta")
                        .HasColumnType("integer");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerformanceDelta")
                        .HasColumnType("integer");

                    b.Property<int>("StressDelta")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoverDelta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CardCombo");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.CardComboTrigger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardComboId")
                        .HasColumnType("uuid");

                    b.Property<string>("CardSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CardComboId");

                    b.HasIndex("CardSlug");

                    b.ToTable("CardComboTrigger");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.CardRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredCardSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("RequiredCardSlug");

                    b.ToTable("CardRequirement");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.CardStatThreshold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<decimal>("PenaltyAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StatName")
                        .HasColumnType("integer");

                    b.Property<int>("Threshold")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardStatThreshold");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.DefeatConditions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MotivationMax")
                        .HasColumnType("integer");

                    b.Property<int>("MotivationMin")
                        .HasColumnType("integer");

                    b.Property<int>("PerformanceMax")
                        .HasColumnType("integer");

                    b.Property<int>("PerformanceMin")
                        .HasColumnType("integer");

                    b.Property<int>("StressMax")
                        .HasColumnType("integer");

                    b.Property<int>("StressMin")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoverMax")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoverMin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DefeatConditions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MotivationMax = 100,
                            MotivationMin = 0,
                            PerformanceMax = 100,
                            PerformanceMin = 15,
                            StressMax = 85,
                            StressMin = 0,
                            TurnoverMax = 80,
                            TurnoverMin = 0
                        });
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<float>("Chance")
                        .HasColumnType("real");

                    b.Property<string>("EventNameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventNameFr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageFr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MotivationDelta")
                        .HasColumnType("integer");

                    b.Property<int>("PerformanceDelta")
                        .HasColumnType("integer");

                    b.Property<int>("StressDelta")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoverDelta")
                        .HasColumnType("integer");

                    b.Property<int>("WeekRangeMax")
                        .HasColumnType("integer");

                    b.Property<int>("WeekRangeMin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.GameConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseXP")
                        .HasColumnType("integer");

                    b.Property<float>("Exponent")
                        .HasColumnType("real");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("integer");

                    b.Property<int>("XPBonusGoodDecision")
                        .HasColumnType("integer");

                    b.Property<int>("XPPerTurn")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GameConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseXP = 2000,
                            Exponent = 2f,
                            MaxLevel = 20,
                            XPBonusGoodDecision = 25,
                            XPPerTurn = 50
                        });
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.Progression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentXP")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Progressions");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.StatsInit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InitialMotivation")
                        .HasColumnType("integer");

                    b.Property<int>("InitialPerformance")
                        .HasColumnType("integer");

                    b.Property<int>("InitialStress")
                        .HasColumnType("integer");

                    b.Property<int>("InitialTurnover")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StatsInits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InitialMotivation = 50,
                            InitialPerformance = 40,
                            InitialStress = 30,
                            InitialTurnover = 20
                        });
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.CardComboTrigger", b =>
                {
                    b.HasOne("DecisionManagerAPI.Models.CardCombo", "CardCombo")
                        .WithMany("Triggers")
                        .HasForeignKey("CardComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DecisionManagerAPI.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardSlug")
                        .HasPrincipalKey("Slug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("CardCombo");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.CardRequirement", b =>
                {
                    b.HasOne("DecisionManagerAPI.Models.Card", "Card")
                        .WithMany("Requirements")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DecisionManagerAPI.Models.Card", "RequiredCard")
                        .WithMany()
                        .HasForeignKey("RequiredCardSlug")
                        .HasPrincipalKey("Slug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("RequiredCard");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.CardStatThreshold", b =>
                {
                    b.HasOne("DecisionManagerAPI.Models.Card", "Card")
                        .WithMany("StatThresholds")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.Event", b =>
                {
                    b.HasOne("DecisionManagerAPI.Models.Card", "Card")
                        .WithMany("Events")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.Progression", b =>
                {
                    b.HasOne("DecisionManagerAPI.Models.Player", "Player")
                        .WithOne("Progression")
                        .HasForeignKey("DecisionManagerAPI.Models.Progression", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.Card", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Requirements");

                    b.Navigation("StatThresholds");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.CardCombo", b =>
                {
                    b.Navigation("Triggers");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.Player", b =>
                {
                    b.Navigation("Progression")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
