// <auto-generated />
using System;
using DecisionManagerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DecisionManagerAPI.Migrations
{
    [DbContext(typeof(DecisionManagerDbContext))]
    [Migration("20260312180259_StatsInit")]
    partial class StatsInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DecisionManagerAPI.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MotivationEffect")
                        .HasColumnType("integer");

                    b.Property<int>("MotivationEffectOnFailure")
                        .HasColumnType("integer");

                    b.Property<int>("PerformanceEffect")
                        .HasColumnType("integer");

                    b.Property<int>("PerformanceEffectOnFailure")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StressEffect")
                        .HasColumnType("integer");

                    b.Property<int>("StressEffectOnFailure")
                        .HasColumnType("integer");

                    b.Property<string>("SuccessMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("SuccessProbability")
                        .HasColumnType("real");

                    b.Property<int>("TurnoverEffect")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoverEffectOnFailure")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.DefeatConditions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MotivationMax")
                        .HasColumnType("integer");

                    b.Property<int>("MotivationMin")
                        .HasColumnType("integer");

                    b.Property<int>("PerformanceMax")
                        .HasColumnType("integer");

                    b.Property<int>("PerformanceMin")
                        .HasColumnType("integer");

                    b.Property<int>("StressMax")
                        .HasColumnType("integer");

                    b.Property<int>("StressMin")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoverMax")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoverMin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DefeatConditions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MotivationMax = 100,
                            MotivationMin = 0,
                            PerformanceMax = 100,
                            PerformanceMin = 15,
                            StressMax = 85,
                            StressMin = 0,
                            TurnoverMax = 80,
                            TurnoverMin = 0
                        });
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<float>("Chance")
                        .HasColumnType("real");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MotivationDelta")
                        .HasColumnType("integer");

                    b.Property<int>("PerformanceDelta")
                        .HasColumnType("integer");

                    b.Property<int>("StressDelta")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoverDelta")
                        .HasColumnType("integer");

                    b.Property<int>("WeekRangeMax")
                        .HasColumnType("integer");

                    b.Property<int>("WeekRangeMin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.GameConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseXP")
                        .HasColumnType("integer");

                    b.Property<float>("Exponent")
                        .HasColumnType("real");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("integer");

                    b.Property<int>("XPBonusGoodDecision")
                        .HasColumnType("integer");

                    b.Property<int>("XPPerTurn")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GameConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseXP = 2000,
                            Exponent = 2f,
                            MaxLevel = 20,
                            XPBonusGoodDecision = 25,
                            XPPerTurn = 50
                        });
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.Progression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentXP")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Progressions");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.StatsInit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InitialMotivation")
                        .HasColumnType("integer");

                    b.Property<int>("InitialPerformance")
                        .HasColumnType("integer");

                    b.Property<int>("InitialStress")
                        .HasColumnType("integer");

                    b.Property<int>("InitialTurnover")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StatsInits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InitialMotivation = 1,
                            InitialPerformance = 50,
                            InitialStress = 50,
                            InitialTurnover = 50
                        });
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.Event", b =>
                {
                    b.HasOne("DecisionManagerAPI.Models.Card", "Card")
                        .WithMany("Events")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.Progression", b =>
                {
                    b.HasOne("DecisionManagerAPI.Models.Player", "Player")
                        .WithOne("Progression")
                        .HasForeignKey("DecisionManagerAPI.Models.Progression", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.Card", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("DecisionManagerAPI.Models.Player", b =>
                {
                    b.Navigation("Progression")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
